### ISSUE TITLE
fithesis3 download

### ISSUE THREAD

**Issue by europ** [Witiko/fithesis3#19]
I would like to report a problem related to fithesis3 download. There is no direct download for fithesis3 archive.  As you can see [here](https://www.fi.muni.cz/tech/unix/tex/fithesis.html.en), you can download fithesis2 as ZIP archive from the official site but the **archive for fithesis3 is missing**.

To download all related source code for fithesis3, it is needed to create an Overleaf project from [fithesis3 Overleaf template](https://www.overleaf.com/latex/templates/fithesis3-for-the-faculty-of-informatics-at-the-masaryk-university-in-brno/qmrtczzjvpfv) and only then, the fithesis3 source code can be downloaded.

**Comment by Witiko** [comment]
You can download the archive of fithesis3 [from CTAN](https://ctan.org/pkg/fithesis) or from the [Releases tab](https://github.com/Witiko/fithesis/releases) of this repository.
However, unlike fithesis1 and fithesis2, fithesis3 is included in your TeX installation (since 2016).
Therefore, you do not need an archive and you can start directly with an [example document](https://ctan.org/tex-archive/macros/latex/contrib/fithesis/example/mu).

Since Overleaf is behind on updating its TeX installation, the Overleaf templates are bundled together with the up-to-date fithesis3 class. However, that's not necessary on your local TeX installation: If you create an Overleaf project from an Overleaf template and then download all files of your project, you can remove the files `fithesis3.cls`, `*markdown.*`, and the directory `fithesis` with no repercussions.

Please, let me know if you have an idea as to how the current solution should be improved.
